name: Fetch Specific JS Files

on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 运行
  workflow_dispatch: # 手动触发

jobs:
  fetch-specific-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch HTML and Extract Main JS URL
        id: fetch_html
        run: |
          # 下载 HTML 文件
          curl -s https://espressif.github.io/esptool-js/ -o page.html

          # 提取动态生成的 JS 文件路径
          SCRIPT_URL=$(grep -oP '(?<=<script src=")index\.\w+\.js(?=" type="module"></script>)' page.html)

          # 拼接完整 URL
          FULL_URL="https://espressif.github.io/esptool-js/$SCRIPT_URL"

          echo "SCRIPT_URL=$SCRIPT_URL" >> $GITHUB_ENV
          echo "FULL_URL=$FULL_URL" >> $GITHUB_ENV

      - name: Download Main JS File
        id: download_main
        run: |
          # 下载主 JS 文件
          curl -s ${{ env.FULL_URL }} -o index.js

      - name: Extract and Download Specific JS Files
        run: |
          # 提取嵌套 JSON 数据
          RAW_TEXT=$(grep -oP 'JSON\.parse\(\K.*(?=\);)' index.js)

          # 清理数据并转换为文件名列表
          FILES=$(echo $RAW_TEXT | tr -d '[]\\"' | tr ',' '\n')

          # 定义关键字
          KEYWORDS=(
  "stub_flasher_32.bc06e557.js"
  "35K3k"
  "stub_flasher_32c2.63c0ddda.js"
  "vZCF2"
  "stub_flasher_32c3.1f4c3acb.js"
  "d4LkX"
  "stub_flasher_32c5.2d91a6ff.js"
  "cJDqv"
  "stub_flasher_32c6.7e3cbb90.js"
  "3OCVy"
  "stub_flasher_32c61.82908af8.js"
  "eXP7h"
  "stub_flasher_32h2.42b7a893.js"
  "fa8eB"
  "stub_flasher_32p4.90dd8add.js"
  "9N6hS"
  "stub_flasher_32s2.38b7c15e.js"
  "gmXBg"
  "stub_flasher_32s3.d91381f3.js"
  "hHpLC"
  "stub_flasher_8266.4f4307c8.js"
  "gbY4J"
  "esp32.3f2660d9.js"
  "jJvTY"
  "esp32c2.11753622.js"
  "ELGPK"
  "esp32c3.566f2292.js"
  "8itJW"
  "esp32c6.5b449d27.js"
  "3qJU9"
  "esp32c61.7aaa628f.js"
  "fk33s"
  "esp32c5.9aff0e3e.js"
  "dJVWW"
  "esp32h2.a06e4253.js"
  "at51o"
  "esp32s3.e35b3ad8.js"
  "2pBtn"
  "esp32s2.315a8ac7.js"
  "cXe3K"
  "esp8266.29587a4a.js"
  "i7djm"
  "esp32p4.433a1fb3.js"
)


          # 遍历文件并匹配关键字
          for FILE in $FILES; do
            for KEY in "${KEYWORDS[@]}"; do
              if [[ $FILE == *"$KEY"* ]]; then
                FILE_URL="https://espressif.github.io/esptool-js/$FILE"
                echo "Downloading $FILE_URL"
                curl -s $FILE_URL -o $(basename $FILE)
              fi
            done
          done

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Download specific JS files and update index.js"
          git push
